//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiSai.RecordServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_key
    {
        public int k_id { get; set; }
        public string k_key { get; set; }
        public System.DateTime k_createDate { get; set; }
        public string k_createSource { get; set; }
        public double k_days { get; set; }
        public System.DateTime k_effectiveDate { get; set; }
        public bool k_use { get; set; }
        public int k_useMenber { get; set; }
    
        public virtual Record_Memberinfo Record_Memberinfo { get; set; }
    }
}
