//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiSai.RecordServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_Memberinfo
    {
        public int ME_ID { get; set; }
        public string ME_NAME { get; set; }
        public string ME_PWD { get; set; }
        public Nullable<int> ME_STATUS { get; set; }
        public Nullable<int> ME_CU_STATUS { get; set; }
        public Nullable<int> ME_TYPE { get; set; }
        public Nullable<int> ME_GR_ID { get; set; }
        public string ME_PHONE { get; set; }
        public string ME_QQ { get; set; }
        public string ME_SEX { get; set; }
        public Nullable<System.DateTime> ME_BIRTHDAY { get; set; }
        public System.DateTime ME_ADD_TIME { get; set; }
        public Nullable<System.DateTime> ME_UPDATE_TIME { get; set; }
        public Nullable<System.DateTime> ME_ENTTIME { get; set; }
        public Nullable<bool> ME_Login { get; set; }
        public string ME_Activation { get; set; }
        public Nullable<System.DateTime> ME_ActivationTime { get; set; }
    }
}
